import React, { useState } from "react";
import axios from "axios";
import "./BulkImportItems.css"; // optional styling file
import { BASE_URL, BULK_IMPORT_PRODUCTS } from "../Constants";

const BulkImportItems = () => {
  const [selectedFile, setSelectedFile] = useState(null);
  const [uploadStatus, setUploadStatus] = useState("");

  const handleFileChange = (e) => {
    setSelectedFile(e.target.files[0]);
  };

  const handleUpload = async () => {
    if (!selectedFile) {
      alert("Please select a file first!");
      return;
    }

    const formData = new FormData();
    formData.append("file", selectedFile);

    try {
      setUploadStatus("Uploading...");
      await axios.post(`${BASE_URL}/${BULK_IMPORT_PRODUCTS}`, formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      setUploadStatus("✅ Upload successful!");
      setSelectedFile(null);
    } catch (error) {
      console.error("Upload error:", error);
      setUploadStatus("❌ Upload failed. Please try again.");
    }
  };

  return (
    <div className="bulk-import-container">
      <h2>Bulk Import Products</h2>
      <p>Please upload your Excel (.xlsx/.csv) file with product details.</p>

      <div className="file-upload-row">
        <input
          type="file"
          accept=".xlsx, .xls, .csv"
          onChange={handleFileChange}
        />
        <button className="upload-button" onClick={handleUpload}>
          📤 Upload File
        </button>
      </div>

      {uploadStatus && <div className="upload-status">{uploadStatus}</div>}

      <div className="import-guidelines">
        <h4>📝 Required Fields in Sheet:</h4>
        <ul>
          <li>Product Name</li>
          <li>Size (optional)</li>
          <li>Stock Quantity (optional)</li>
          <li>Supplier Name (optional)</li>
          <li>Buy Price</li>
          <li>MRP</li>
          <li>Category</li>
          <li>Tax % (optional)</li>
        </ul>
        <p>⚠️ Barcode will be auto-generated by the system.</p>
      </div>
    </div>
  );
};

export default BulkImportItems;
